### ISSUE TITLE
Find /stoa0149b/stoa001/stoa0149b.stoa001.opp-lat1.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/csel-dev#128]
The work with this URN (Hilary, Tractatus super psalmos) has somehow been overwritten by this one.  We may need to extract it manually from the CSEL23.xml file.

**Comment by annettegessner** [comment]
Could this have something to do with our splitting-problem and/or the fact, that this file has been overwritten with a work with almost exactly the same work_ID: stoa0149p.stoa001 ("p" instead of "b")?

**Comment by annettegessner** [comment]
And work stoa0149b.stoa001 can be found in CSEL Vol. 22 (the "wrong" work with "p", which has overwritten this one, is in Vol. 23).

**Comment by sonofmun** [comment]
Would it be possible to copy the body of the word from CSEL 22 to the existing version of stoa0149b.stoa001..., changing the TEI header as necessary?  Or will we need to take more drastic measures here?

**Comment by annettegessner** [comment]
I am already looking into this: It should be no problem to copy the text, but I am unsure about the information in the header (e.g. the RefsDecl). IÄll have a look and then ask, if I need help.

**Comment by sonofmun** [comment]
Perfect.  Just let me know if you need help.

**Comment by annettegessner** [comment]
Did it! B-) 
Pull request #145

**Comment by sonofmun** [comment]
Excellent.  The text now passes.  Closing this issue.
