### ISSUE TITLE
Paragraphs in stoa0114a.stoa003.opp-lat1

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#182]
In this files we have the structure: book, poem, line.
But in some of the poems, we have a paragraph in front of the lines as some kind of preface. Do we have to number those paragraphs as n="pr" and add them to the RefsDecl?
This file passed the hook test, so it doesn't seem to raise a problem, but I am not sure, abut how these paragraphs will be displayed and how they can be referenced ...

**Comment by sonofmun** [comment]
For now, I think I would leave them unreferenced since we don't really know whether anyone will want to cite by them or not.  If we find out later that people want to cite by them, we can add them into the refsDecl later.

**Comment by annettegessner** [comment]
So they are displayed in the text, but you can't reference them, right? I think we can live with that for now.
