### ISSUE TITLE
add work_ID and full URN for Epitaphium Ennodii 

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#193]

**Comment by AlisonBabeu** [comment]
I've created a work ID(phi9500.phi035) and full URN (urn:cts:latinLit:phi9500.phi035.opp-lat1) for this work. I've also created a catalog record for it as well that is now in catalog_pending (https://github.com/PerseusDL/catalog_pending/blob/master/mods/Anonymi%20Epici%20et%20Lyrici/Anonymi.CSEL6.EpitaphiumEnnodi.mods.xml).

**Comment by annettegessner** [comment]
check

**Comment by sonofmun** [comment]
This work has been added.  I will close this issue and we can add another one if the file under the correct URN fails the Hook tests.
