### ISSUE TITLE
merge text from Vol. 34/1 and 34/2 with same urn:cts:latinLit:stoa0040.stoa011.opp-lat2

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#219]

**Comment by pmsprenger** [comment]
I merged the two files. In order not to break something I didn't touch the old files, yet.
See here for what I would do: https://www.dropbox.com/s/qs8wznpz0tybgjg/new_merged_stoa0040.stoa011.opp-lat2.xml?dl=0
Is this doable?

**Comment by annettegessner** [comment]
worked fine after fixing xPath - done and passing hook test
