### ISSUE TITLE
add full URN for Excerpt of stoa0040.stoa054 in CSEL Vol. 5

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#221]
The text is just an excerpt of Augustin's "De Natura et Gratia", which has the full URN 
urn:cts:latinLit:stoa0040.stoa054.opp-lat1
and thus needs it's own full URN (urn:cts:latinLit:stoa0040.stoa054.opp-lat2 maybe?).

Don't merge text from Vol. 5 and Vol. 60 (it had the same URN for some time in our spreadsheet)!

**Comment by AlisonBabeu** [comment]
urn:cts:latinLit:stoa0040.stoa054.opp-lat2  would be the full URN for this work.

**Comment by annettegessner** [comment]
fix CTS

**Comment by annettegessner** [comment]
passes hook test now - closing issue
