### ISSUE TITLE
Figure out how to deal with volume 58

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/csel-dev#234]
This volume is made up only of prologue and appendix elements, so there is no work here.  We need to figure out whether and how to include it in this repo.

**Comment by annettegessner** [comment]
My suggestion is to "ignore" volume 58, i.e. keep the indices like we do with all volumes, but since there are no subtype="work" textparts here, there is nothing to make anything CTS compliant or anything.

**Comment by sonofmun** [comment]
This then pushes the question out one level: what should we do with all of the front and back matter, etc.?  Should we dump it all in its own folder on the master branch?  Should we create another branch with all that data in it?  Or perhaps a completely different, non-CTS repository?  What are your thoughts here, @PonteIneptique ?

**Comment by annettegessner** [comment]
Very good question, Matt!
I don't think that many of our users will have those files as a priority, but it is still nice to have the stuff somewhere to have a look at if needed. I just hope those files are not too confusing to look at since e.g. for the MSS- or TOC-files it could be hard to figure out, what work they belonged to ...

**Comment by PonteIneptique** [comment]
Can you link to me the volume 8 so I that I can understand ?

**Comment by sonofmun** [comment]
https://github.com/OpenGreekAndLatin/csel-dev/tree/old-files/CSEL58
The full xml volumes are all in the old-fiiles branch.

**Comment by PonteIneptique** [comment]
Are they classical texts or modern commentaries ?

**Comment by sonofmun** [comment]
Good question.  @annettegessner Do you know?  My feeling is that they might be both but probably primarily modern commentaries, appendices, etc.

**Comment by annettegessner** [comment]
I am pretty sure, those are modern additions of the editor.

**Comment by sonofmun** [comment]
I think we have answered this question. Volume 58 is in the Volumes subfolder for now. If we decide to revisit this, we can reopen the issue.
