### ISSUE TITLE
Check structure of stoa0114a.stoa003.opp-lat1.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/csel-dev#253]
There are the following strange structures in this file:

```
<div n="1" subtype="book">
    <div n="9" subtype="poem">
        <div n="1" subtype="main">
            <l n="1">
            ...
            <l n="170">
        </div>
    </div>
</div>

<div n="2" subtype="book">
    <div n="107" subtype="poem">
        <div n="1" subtype="poem">
        </div>
    </div>
</div>

<div n="2" subtype="book">
    <div n="150" subtype="poem">
        <div n="1" subtype="poem">
        </div>
    </div>
</div>
```

In the first, an extra \<div subtype="main"\> and in the second two a \<poem\> as a child of \<poem\>.  I don't know if this needs to be corrected, but it seems quite strange and makes the xpath a bit iffy as to whether it will always work.

**Comment by annettegessner** [comment]
In this work, we have books containing poems. But some of these poems don't just contain lines, but also have some kind of preface written in prose. To avoid conflicts, we added a level to separate the prose part from the poems and called this level "main". E.g.: 
`<div n="1" subtype="book" type="textpart">
    <div n="9" subtype="poem" type="textpart">
        <div n="pr" subtype="main" type="textpart"> (containing the prose preface)
        <div n="1" subtype="main" type="textpart"> (containing the lines <l> of the poem)´

We didn't add this extra level "main" to any of the poems, just those with prefaces.
I figured this might cause problems, but at the moment, I am not sure about how else to handle this problem. Any ideas?

**Comment by annettegessner** [comment]
One (not very pretty) thing I could think of: 
The prose prefaces are quite long (containing footnotes and everything) and are momentarily contained in one paragraph. But maybe we could rename this paragraph to 
    <l n="pr">
and delete the "main"-level, leaving levels "book", "poem" (no more "main") and "line"?

**Comment by annettegessner** [comment]
changed they way described - passing hook test
