### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#276]
There are for some reason three works of CSEL missing on GitHub, all from CSEL Volume 25_1:

urn:cts:latinLit:stoa0040.stoa017.opp-lat1 (Augustine - Contra Adimantum)
urn:cts:latinLit:stoa0040.stoa024.opp-lat1 (Augustine - Contra Faustum)
urn:cts:latinLit:stoa0040.stoa064.opp-lat1 (Augustine - De Utilitate Credendi)

They are definitely in the unsplitted old file and are properly tagged.

**Comment by sonofmun** [comment]
Added the files with PR #278 Now we need to make them compliant.
