### ISSUE TITLE
works not showing up on NEMO: check xPath, remove @subtype

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#277]
Here are the links to some of the works, that are not showing up on Nemo:
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa024/opp-lat1
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa004/opp-lat2
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa004/opp-lat3
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa004/opp-lat1
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0149b/stoa002/opp-lat1

Thibault wrote, this might be an issue with the xPath and the hook test needs to be adjusted to check, if lower levels have deeper xPath. (E.g.: citation node states letter > section > chapter, but chapter does not take section into account.) 
http://services2.perseids.org/exist/restxq/cts?inv=nemo&request=GetValidReff&urn=urn:cts:latinLit:stoa0162.stoa004.opp-lat1&level=3 "

Removing @subtype in the xPath might help!

**Comment by annettegessner** [comment]
check after PR #286 is merged

**Comment by annettegessner** [comment]
@PonteIneptique: We just checked the refsDecls of all CSEL files, deleted every @subtype in the xPath and corrected the files if necessary. Do we have to wait for an update or something? The files are still not showing up on Nemo. Otherwise: Any ideas, what to try next?

**Comment by PonteIneptique** [comment]
We are not updating this instance anymore. You should have a look at the tutorials to get Nemo working on your own computer : http://capitains.github.io/pages/tutorials

**Comment by sonofmun** [comment]
Do we not have a web instance of Nemo anywhere? What happened to the discussions with Fabian to get a server up for Nemo?

**Comment by PonteIneptique** [comment]
It did not go anywhere, no answer since I last pinged (couple weeks ago) for the last time (probably pinged 3 times ...)

**Comment by annettegessner** [comment]
Works are now showing up on Nemo (checked with local Docker version).
Closing issue.
