### ISSUE TITLE
Add xml:lang attribute to work nodes in /data/textgroup/work/__cts__.xml

### ISSUE THREAD

**Issue by PonteIneptique** [OpenGreekAndLatin/csel-dev#283]
Right now, work level node has no xml:lang attribute.
To be fair, it was not tested by Hook :)

**Comment by PonteIneptique** [comment]
@sonofmun I think a script would do the trick to do this ;)

**Comment by sonofmun** [comment]
@PonteIneptique I am not sure where you are looking. E.g., when I look at /stoa0040a/stoa002/__cts__.xml, there are xml:lang attributes on every node that has text in it. Should there be xml:lang attributes on nodes with no text? Or did I just choose the wrong file? I would assume, though, that if they are here then they are everywhere.
I should say, though, that they don't always appear to be correct, e.g., in the file above the xml:lang on the title node should be "lat".

**Comment by PonteIneptique** [comment]
No worries, it's an error Hook did not check : the ti:work should have an xml:lang stating the original language of the work 

```xml
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:latinLit:stoa0034" urn="urn:cts:latinLit:stoa0034.stoa001">
  <ti:title xml:lang="eng">Arnobii adversus nationes Libri VII</ti:title>
  <ti:edition workUrn="urn:cts:latinLit:stoa0034.stoa001" urn="urn:cts:latinLit:stoa0034.stoa001.opp-lat1">
    <ti:label xml:lang="eng">Arnobii adversus nationes Libri VII</ti:label>
    <ti:description xml:lang="eng">Arnobius of Sicca, Arnobii adversus nationes Libri VII</ti:description>
  </ti:edition>
</ti:work>
```
should be

```xml
<ti:work xml:lang="lat" xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:latinLit:stoa0034" urn="urn:cts:latinLit:stoa0034.stoa001">
  <ti:title xml:lang="eng">Arnobii adversus nationes Libri VII</ti:title>
  <ti:edition workUrn="urn:cts:latinLit:stoa0034.stoa001" urn="urn:cts:latinLit:stoa0034.stoa001.opp-lat1">
    <ti:label xml:lang="eng">Arnobii adversus nationes Libri VII</ti:label>
    <ti:description xml:lang="eng">Arnobius of Sicca, Arnobii adversus nationes Libri VII</ti:description>
  </ti:edition>
</ti:work>
```

**Comment by sonofmun** [comment]
Really? I thought the xml:lang attribute was a description of the language of the text in the node and not a description of the item. At least that is what this would lead me to believe: https://www.w3.org/International/questions/qa-when-xmllang.en. Am I wrong here?

**Comment by sonofmun** [comment]
If it does need to be added to the \<ti:work\> tag, then you should update here (http://capitains.github.io/pages/guidelines.html#work-ctsxml) to reflect that.

**Comment by PonteIneptique** [comment]
It does need to be added, and the guidelines does need to be updated. I do not know if you're wrong, it just the way it's done by CTS :/

**Comment by sonofmun** [comment]
That is really strange because we could also have translations listed in the work level \_\_cts\_\_.xml files and then having an xml:lang attribute of "lat" on the \<ti:work\> node would be ridiculous (I think). I will go ahead and add it if it is necessary but it seems strange that the CTS standard would need that.

**Comment by PonteIneptique** [comment]
I know the way is done is a bit ridiculous but here is how it works : 

- ti:work have an xml:lang. It represents the notional lang behind the notional work. Technically, as an xml node, it does not have text. So it could cover the lang of the object described by the node.
- ti:edition have no xml:lang because they are representation of the work. Technically, this is a big mistake of CTS because it denies multilingual notional work, such as the bible or Beckett's work for example.
- ti:translation have an xml:lang which represents the translation language and overwrites the notional work language inheritance.
