### ISSUE TITLE
different subtypes (p and l) in stoa0223.stoa001.opp-lat1

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#287]
In this file we have the structure "poem" > "line",
but the first "poem" is a "preface", which doesn't contain lines, but a paragraph.
What do we do in a case like this? 
Define the alternative in the refsDecl somehow or try to change the text to match the rest (i.e. make the paragraph a line or something like this)?

**Comment by annettegessner** [comment]
with PR #286 I changed the paragraph "p" to an "l n="1"", but it didn't work (maybe due to the linebreaks?)

link to the file: 
https://raw.githubusercontent.com/OpenGreekAndLatin/csel-dev/master/data/stoa0223/stoa001/stoa0223.stoa001.opp-lat1.xml

hook test says:
Passage level parsing failed
38 found
Duplicate references found : 1
9329 found

**Comment by sonofmun** [comment]
@annettegessner I think I would not try to go further down than the poem level for this first poem. I.e., you would have poem @n="1" with no lines and no deeper citation level. Then the other poems would have their normal lines. It should, at least, be CapiTainS compliant.

**Comment by sonofmun** [comment]
@annettegessner And since you have the open pull request with this file, I would prefer that you go ahead and change it and add it to the PR so that everything will still be 100%.

**Comment by annettegessner** [comment]
Interesting! I'll do this!

**Comment by annettegessner** [comment]
I remember us having a similar problem in [stoa0058.stoa001.opp-lat3.xml](https://github.com/OpenGreekAndLatin/csel-dev/blob/master/data/stoa0058/stoa001/stoa0058.stoa001.opp-lat3.xml)

I'd like to try something like we did in this document:
`<cRefPattern n="section|line" matchPattern="(.+).(.+).(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='$1']/tei:div[@n='$2']/*[self::tei:div or self::tei:l][@n='$3'])"/>`

**Comment by sonofmun** [comment]
Fixed through @annettegessner 's ingenuity.

**Comment by annettegessner** [comment]
Sweet! Let's keep that in mind, in case it will happen again.
And I think I remember Simona solving this problem back in the day, so my "ingenuity" is remembering something about it. ;-)
