### ISSUE TITLE
xml:lang

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/csel-dev#291]
Question at @PonteIneptique:

During the CTS training, you told us to add an element describing the language to the edition-div-tag like this:
`<div type="edition" xml:lang="lat" n="urn:cts:latinLit:phi0978.phi001.opp-lat8">`

It seems, we haven't done this in any of our repositories yet. At the moment our files include the language information in the header, but no attribute in the edition-div. It looks like this:
`<profileDesc>
      <langUsage>
        <language ident="la">Latin</language>
      </langUsage>
    </profileDesc>
</teiHeader>
<text>
<body>
<div type="edition" n="urn:cts:latinLit:stoa0028e.stoa001.opp-lat1">``

Should we change this to include the `xml:lang="lat"` like the way you told us?

**Comment by annettegessner** [comment]
if yes, just merge PR #292 and I'll do this for PL and First1KGreek too

**Comment by sonofmun** [comment]
I think you meant to direct this question to @PonteIneptique

**Comment by thibault** [comment]
Wrong @thibault indeed.

**Comment by annettegessner** [comment]
Argh, sorry @Thibault, my bad!

**Comment by PonteIneptique** [comment]
Hey @thibault, nice to meet you, sorry for the trouble ;)

@annettegessner Yes, iso on three characters, `xml:lang="lat"` on `div[@type="edition"]` (Also for `<language ident="lat">Latin</language>`.

BTW, I have also see in First1KYear a lot of text stating Latin text content in language but they only had Greek. Maybe worth checking :)

**Comment by thibault** [comment]
@annettegessner No problem. See ya.

**Comment by annettegessner** [comment]
There seems to be a lot of "la" going on, e.g.
`<listBibl xml:lang="la">` or `<name xml:lang="la">`
I guess, this has all to be changed to "lat", too.

**Comment by PonteIneptique** [comment]
Exactly @annettegessner

**Comment by annettegessner** [comment]
Sorry for bothering you again, @PonteIneptique, but I just looked this up and the Epidoc guideline states it's "la" for Latin:
http://www.stoa.org/epidoc/gl/latest/supp-language.html
Are you sure about changing all the "la" into "lat"?

**Comment by PonteIneptique** [comment]
Hmm... I'd like @balmas to weight in this discussion here because we adopted three chars long. And I believe three chars long are much better than 2 (including for dialect and stuff).
@annettegessner Can you see if it fails passing test if you set it to "lat" ?

**Comment by sonofmun** [comment]
The files are passing with, e.g., https://github.com/OpenGreekAndLatin/csel-dev/blob/08856f4e6239c98da493d12473e6cc86ae5b8edf/data/phi9500/phi035/phi9500.phi035.opp-lat1.xml#L98-Lundefined

**Comment by balmas** [comment]
We have been using 3 chars, although I think there is some room for debate on this topic. At one point there was a recommendation that we only use 3 chars when the 2 char code wasn't specific enough.  Technically I think that is the official ISO recommendation. We should probably support either.

**Comment by PonteIneptique** [comment]
So, to make it short, it should not be high in the list of priorities (I think cleaning the text that states another language is much more important : 
[this text for example](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0363/tlg007/tlg0363.tlg007.opp-grc2.xml#L74-L75) has clearly not Latin :) except maybe in footnote

**Comment by annettegessner** [comment]
There's no Epidoc-problem nor does any of the files fail the hook test, if I set it all to "lat".

**Comment by sonofmun** [comment]
Can I finally close this issue?

**Comment by PonteIneptique** [comment]
![fjprxx](https://cloud.githubusercontent.com/assets/1929830/15542550/8d73a48c-2291-11e6-8622-746b9aa03ae6.jpg)

**Comment by annettegessner** [comment]
Close the issue, impatient Matt. ;-) 
Thanks everybody, everything is on "lat" now and I'll start by cleaning out the right language.
