### ISSUE TITLE
(stoa0040.stoa072.opp-lat1 ) Fix typo in CTS file in title and label of work

### ISSUE THREAD

**Issue by nevenjovanovic** [OpenGreekAndLatin/csel-dev#309]
The CTS file at csel-dev/data/stoa0040/stoa072/__cts__.xml has unwanted letter transpositions:
```xml
<ti:title xml:lang="eng">Psamlus Contra Parten Donati</ti:title>
  <ti:edition workUrn="urn:cts:latinLit:stoa0040.stoa072" urn="urn:cts:latinLit:stoa0040.stoa072.opp-lat1">
<ti:label xml:lang="eng">Psamlus Contra Parten Donati</ti:label>
```
The "Psamlus Contra Parten" in ti:title and ti:label should be replaced with "Psalmus Contra Partem".
The typo is also visible at https://scaife-cts.perseus.org/api/cts?request=GetPassage&urn=urn:cts:latinLit:stoa0040.stoa072.opp-lat1 and elsewhere on Scaife.

**Comment by AlisonBabeu** [comment]
Hi @nevenjovanovic. Thanks for finding this. A comprehensive review of the headers and work titles in CSEL should be starting soon as there are a lot of issues like this!

**Comment by AlisonBabeu** [comment]
I'm closing this issue since it has long been resolved.
