### ISSUE TITLE
Fix /stoa0104p/stoa021/stoa0104p.stoa021.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/csel-dev#83]
There appear to be real problems with this file.  It could not even be ingested into MyCapitain.  Check it to see what the problems are.

**Comment by planatheisa** [comment]
The XML file itself seems fine. However there is no "__cts__.xml" file.

**Comment by sonofmun** [comment]
I will need to look at this and figure out what is going on.  It is probably with my script.

**Comment by sonofmun** [comment]
We have no edition URN for this edition, that is why the __cts__.xml file is missing.  I assume that it will be urn:cts:latinLit:stoa0104p.stoa021.opp-lat1.  @AlisonBabeu could you confirm this?

**Comment by sonofmun** [comment]
I have set up the __cts__.xml file and changed the .xml file for the test with the assumption that the edition urn above is correct.  Once Alison confirms this, I will push these changes.

**Comment by annettegessner** [comment]
I'll see what I can do with this one.

**Comment by annettegessner** [comment]
trying to fix this issue and #165

**Comment by annettegessner** [comment]
waiting for confirmation

**Comment by AlisonBabeu** [comment]
Hi folks, I'm sorry for my delay on answering this. I still haven't figured out how to get Github notifications to push to me automatically. Yes, that is the correct edition level URN for this work as it will be the first one we have.

**Comment by annettegessner** [comment]
passes hook test now
