### ISSUE TITLE
Fix XML header for /stoa0149p/stoa001/stoa0149p.stoa001.opp-lat1.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/csel-dev#98]
Hook simply says that the naming conventions are incorrect.  What exactly does this mean @PonteIneptique ?

**Comment by PonteIneptique** [comment]
urn work identifier != filename

**Comment by PonteIneptique** [comment]
| ----------------- | -------------- |
| Urn in the file | urn:cts:latinLit:stoa0149p.stoa001.opp-lat1 |
| Filename       | stoa0149b.stoa001.opp-lat1.xml |
| ----------------- | -------------- |

**Comment by sonofmun** [comment]
Should be easy to fix!  Someone pick it up.

On 13.11.2015 14:56, Thibault Clérice wrote:
>
> | ----------------- | -------------- |
> | Urn in the file | urn:cts:latinLit:stoa0149p.stoa001.opp-lat1 |
> | Filename | stoa0149b.stoa001.opp-lat1.xml |
> | ----------------- | -------------- |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenGreekAndLatin/csel-dev/issues/98#issuecomment-156436443>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by sonofmun** [comment]
Good.  So we need to figure out which URN is correct and change it in 
the file (and in our Google spreadsheet).

On 13.11.2015 14:56, Thibault Clérice wrote:
>
> | ----------------- | -------------- |
> | Urn in the file | urn:cts:latinLit:stoa0149p.stoa001.opp-lat1 |
> | Filename | stoa0149b.stoa001.opp-lat1.xml |
> | ----------------- | -------------- |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenGreekAndLatin/csel-dev/issues/98#issuecomment-156436443>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by planatheisa** [comment]
I've been looking at it. The file should be named 149p (see CSEL-dev list line 136). Another thing that is bothering me: In the sourceDesc it gives a totally different title and author (Heptateuchos and Cyprianus resp.). Why is that and what do we do with it.

**Comment by planatheisa** [comment]
OK. I know why. Same volume, different work. So I change it to the correct one?

**Comment by planatheisa** [comment]
Also: I had told this Simona before. The <idno type="filename">  still gives the unsplitted filename (CSEL23.xml). This is probably the case for all splitted files. Is this a problem or not?

**Comment by sonofmun** [comment]
@planatheisa First, check out /stoa0149p/stoa001/stoa0149p.stoa001.opp-lat1.xml.  So the same work exists here with the correct filename and URN.  So go into  /stoa0149p/stoa001/stoa0149p.stoa001.opp-lat1.xml and change the filename to the correct one (not CSEL23.xml), change the title and author name and make sure that the correct values are given for the @ref attribute for both of these.  
I will need to start a new issue for /stoa0149b/stoa001/stoa0149b.stoa001.opp-lat1.xml because it appears that the work that has that URN (Hilary, Tractatus super psalmos) is missing.  It was probably overwritten somehow by this other one.  We will need to do some research there.

**Comment by planatheisa** [comment]
I'd actually rather copy the (wrong) 149b to 149p because I added line numbers there, which do not exist in the current 149p. When I sent it to Annette it was still called 149p, but it seems it replaced the wrong document in the end.

**Comment by planatheisa** [comment]
If no other changes occured; i could also upload the 149p from my netbook, because I kept it.

**Comment by sonofmun** [comment]
Sounds good.

**Comment by sonofmun** [comment]
Either one of these is fine. No one else should be working in this file

**Comment by planatheisa** [comment]
Committed. Please check reference for the author, I hope it's the right one.

**Comment by sonofmun** [comment]
This file passes the Hook tests now.  Closing the issue.
